config/routes.rb
BatchManagementSystem::Application.routes.draw do

  resources :requests




devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :controller => {:invitations => 'devise/invitations'},
    :root_path => 'home#index'    
  }
  
  resources :questions
match '/:question_id/option' => 'questions#option', :via =>[:get, :post], as: :option
  resources :trainers do
    collection do
      delete 'destroy_multiple'
    end
  end
match '/studentinfo' => 'enquiries#studentinfo', via: :get
resources :enquiries do
    collection do
      delete 'destroy_multiple'
    end
  end
match '/welcome' => 'home#welcome', :via => :get, as: :welcome

    match'/grades/:grade_id/fees' => 'grades#fees', via: :get, as: :fees
    resources :sponsors do
    collection do
      delete 'destroy_multiple'
    end
  end

      match'/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  resources :grades, :shallow => true do
collection do
     delete 'multipledelete'
end
    resources :batches do
collection do
     delete 'multipledelete'
end
      resources :lectures
    end
      resources :exams
      resources :lessons do
      resources :topics
    end

  end
 resources :subjects do
   collection do
     delete 'destroy_multiple'
   end
 end

  resources :states do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :cities do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :students do
    collection do
      delete 'destroy_multiple'
       post 'assign_batch_multiple'
    end
  end

  match'/students/:student_id/banmultiple' => 'students#banmultiple', :via => [:get, :put], as: :banmultiple
  match '/index_action' => 'students#index_action', :via => :get
  match '/grades/:grade_id/batches' => 'batches#index' 
  match'/students/:student_id/addmition' => 'students#addmition', :via => [:get, :post], as: :addmition

  match '/assign_batch' => 'students#assign_batch', :via => [:get, :post]
  match '/addgrade' => 'students#addgrade', :via => [:get, :post], as: :addgrade
  match '/student/:state_id/city' => 'students#city', :via => :get, as: :city
  match '/students/:grade_id/assign_batch_multiple' => 'students#assign_batch_multiple', :via => [:get, :post], as: :assign_batch_multiple
  match '/grade/:grade_id/subjects' => 'grades#subjects_list', :via => [:get, :post], as: :subjects_list
  match '/grade/:grade_id/batch/:batch_id/students' => 'batches#assignbatch', :via => [:get, :post], as: :assignbatch
    match '/:student_id/document' => 'students#document', via: :get
  match '/batch/:batch_id/assigntrainers' => 'batches#assigntrainers', :via => [:get, :post], as: :assigntrainers
  match '/exam/:exam_id/setpaper' => 'exams#setpaper', :via => [:get, :post], as: :setpaper
  match '/exam/:exam_id/setsubject' => 'exams#setsubject', :via => [:get, :post], as: :setsubject
 match '/exam/:exam_id/setting' => 'exams#setting', :via => [:get, :put], as: :setting
 match '/exam/:exam_id/currentpaper' => 'exams#currentpaper', :via => [:get, :put], as: :currentpaper
 match '/exam/:exam_id/giveexam' => 'exams#giveexam', :via => [:get, :post], as: :giveexam
  match '/result_id/result' => 'exams#result', :via => :get, as: :result
  match '/student/:student_id/allresults' => 'students#allresults', :via => :get, as: :allresults




  match '/grades/batch/:batch_id/attendents' => 'batches#attendents', :via => [:get, :post], as: :attendents

  match'/marking_pattens/:marking_patten_id' => 'grades#destroy_marking_patten', :via => :delete, as: :destroy_marking_patten
  match '/studentinfo' => 'enquiries#studentinfo', via: :get
  match'/grade/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  match'/enquiry/:enquiry_id/students/new' => 'students#enrollement', :via => :get, as: :enrollement


match '/trainers/:trainer_id/ability' => 'trainers#ability', :via => [:get, :post], as: :ability
match 'trainers/:trainer_id/display' => 'trainers#display', :via =>  :get, as: :display
match 'lectures/:lecture_id/details' => 'lectures#details', :via =>  :get, as: :details
match '/calenderhelp' => 'home#calenderhelp', :via => :get


root :to => 'home#index'









end


app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :batch
  has_many :presenties
  has_many :students, :through => :presenties
  attr_accessible :assign_homework, :session_date, :remarks, :attribute_presenties
accepts_nested_attributes_for :presenties
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  load_and_authorize_resource

  def index
    @batch = Batch.find(params[:batch_id])
    @lectures = @batch.lectures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lectures }
    end
  end

  def show
    @lecture = Lecture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lecture }
    end
  end

  def new
    @batch = Batch.find(params[:batch_id])
    @lecture = @batch.lectures.build
    #@lecture = Lecture.new
    @presenty = Presenty.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lecture }
    end
  end

  def edit
    @lecture = Lecture.find(params[:id])
    @presenty = @lecture.presenties
  end

  def create
    @batch = Batch.find(params[:batch_id])
    @lecture = @batch.lectures.build
    @lecture.session_date = params[:lecture][:session_date]
    @lecture.assign_homework = params[:lecture][:assign_homework]
    @lecture.remarks = params[:lecture][:remarks]
p "The Var is,"
p @lecture
p "The params is,"
p params
p "students var is,"
p params[:students]
    if params[:presenty] == nil
render action: "new" 
else
params["students"].each do |student_id|
p "Loop is,"
p student_id
p "Presenty is,"
p params[:presenty]
p "wove nice" if params[:presenty].has_key?(student_id)
  @presenty = @lecture.presenties.build
if params[:presenty].has_key?(student_id)
@presenty.student_id = student_id

  if params[:presenty][student_id].has_key?(:done_homework)
    @presenty.done_homework = params[:presenty][student_id][:done_homework]
  end
  if params[:presenty][student_id].has_key?(:attendent)
    @presenty.attendent = params[:presenty][student_id][:attendent]
  end
end#student_id key check 

end

    respond_to do |format|
     if  @lecture.save
p "my var"
        format.html { redirect_to batch_lectures_path, notice: 'Session was successfully created.' }
        format.json { render json: @lecture, status: :created, location: @lecture }
      else
p "Error in var"
p @lecture
        format.html { render action: "new" }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end
end

  def update
    @lecture = Lecture.find(params[:id])
p "the lecture var is, #{@lecture}"
#@presenty =@lecture.presenties.build
p "the params is,"
p params
p "The presenty is,"
p "second params is,"
   p params[:presenty]
#@presenty.update_attributes(params[:presenty][111])
    respond_to do |format|
p "the lecture var"
p @lecture

      if @lecture.update_attributes(params[:lecture])
        format.html { redirect_to grades_path, notice: 'Lecture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
end

  

  def destroy
    @lecture = Lecture.find(params[:id])
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to batch_lectures_url }
      format.json { head :no_content }
    end
  end
  def details
    @lecture = Lecture.find(params[:lecture_id])
  end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.haml
- content_for :javascript do
  = javascript_include_tag 'setup_lecture_session_date', 'lectures'
= simple_form_for ([@batch, @lecture]) do |f|
  = f.error_notification

  .form-inputs
    %table.table
      %tr
        %th 
        %th Assign Homework
        %th Session Date
        %th Add Remarks
      %tr
        %td= f.hidden_field :batch_id
        %td= f.input :assign_homework, as: :boolean
        %td
          = f.input :session_date, :label => "Session Date" do
            = f.input_field :session_date, :as => :datepicker, :readonly => true
            %a{:href => '#', :id => 'imgCalendar_session_date', :class => 'datePicker'}
              = image_tag('Calendar_scheduleHS.png', :alt => 'Pick date from calendar' )
              = link_to 'Need Help?', calenderhelp_path, "data-toggle" => "modal", "data-target" => "#calendermodel", :class => "lnkApprove", :remote => true, :class => 'btn btn-mini'
        %td= f.input :remarks, :as => :text

  %h2 Student Attendents
  %table.table
    %tr
      %th
      %th Student Name
      %th{:id=>"attendence"} Student Attendents
      %th{:id=>"homework"}  Homework Done
    - if @batch.students.size > 0

      - @batch.students.each do |student|
        %tr
          %td= hidden_field_tag "students[]", student.id
          %th{:id=>"s_#{student.id}"}= student.first_name + " " + student.last_name
          %td.cls{:headers=>"s_#{student.id} attendence"}= check_box_tag "presenty[#{student.id}][attendent]"
          %td.vishal{:headers=>"s_#{student.id} homework"}= check_box_tag "presenty[#{student.id}][done_homework]"
  = f.submit "Create new session"

  %div{:id => 'calendermodel', :class => 'modal hide fade-calenderhelp', :tabindex => '-1', :role => 'dialog', 'aria-labelledby' => 'myModalLabel', 'aria-hidden' => 'true'}
    %div{:class => 'modal-header-calenderhelp'}
      %h3 Instructions:      

    %div{:class => 'modal-body'}
      %div{:class => 'modal-footer-calenderhelp'}


app/views/lectures/_parshel.html.haml
- content_for :javascript do
  = javascript_include_tag 'lectures'

= simple_form_for ([@batch, @lecture])  do |f|
  = f.error_notification

  .form-inputs
    %table.table
      %tr
        %th 
        %th Assign Homework
        %th Session Date
        %th Add Remarks
      %tr
        %td= f.input :assign_homework, as: :boolean
        %td= f.input :session_date, :label => "Session Date", :as => :datepicker, :readonly => true
        %td= f.input :remarks, :as => :text
  %h2 Student Attendents
  %table.table
    %tr
      %th
      %th Student Name
      %th{:id=>"attendence"} Student Attendents
      %th{:id=>"homework"}  Homework Done
    - @lecture.students.each do |student|
      %tr
        %td= student.first_name.capitalize + " " + student.last_name.capitalize
        - @lecture.presenties.each do |presenty|
          %td= presenty

app/views/lectures/details.html.haml
- content_for :javascript do
  = javascript_include_tag 'lectures'
%h1 Student details
%table.table
  %tr
    %th Student Name
    %th Honework done
    %th Attendence
  - @lecture.presenties.each do |presenty|
    %tr
      %td= presenty.student.first_name.capitalize + " " + presenty.student.last_name.capitalize
      - if presenty.done_homework
        %td yes
      - else
        %td no
      - if presenty.attendent
        %td yes
      - else
        %td no

%br

app/views/lectures/edit.html.haml
%h1 Editing lecture

= render 'parshel'

= link_to 'Show', @lecture

app/views/lectures/index.html.haml
- content_for :javascript do
  = javascript_include_tag 'lectures'
%h1 Showing all sessions  witch is for #{@batch.title}

%table.table

  %tr

    %th Session date
    %th Assign Homework

    %th Description

  - @lectures.each do |lecture|

    %tr

      %td= lecture.session_date

      - if lecture.assign_homework

        %td Yes

      -else

        %td no
      %td= lecture.remarks
      %td= link_to "Show details", details_path(lecture)

%br

= link_to "Create New Lecture", new_batch_lecture_path

app/views/lectures/new.html.haml
%h1 New lecture

= render 'form'

= link_to 'Back', batch_lectures_path

app/views/lectures/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_lecture_path(@lecture)
\|
= link_to 'Back', batch_lectures_path