config/routes.rb
BatchManagementSystem::Application.routes.draw do

  resources :requests




devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :controller => {:invitations => 'devise/invitations'},
    :root_path => 'home#index'    
  }
  
  resources :questions
match '/:question_id/option' => 'questions#option', :via =>[:get, :post], as: :option
  resources :trainers do
    collection do
      delete 'destroy_multiple'
    end
  end
match '/studentinfo' => 'enquiries#studentinfo', via: :get
resources :enquiries do
    collection do
      delete 'destroy_multiple'
    end
  end
match '/welcome' => 'home#welcome', :via => :get, as: :welcome

    match'/grades/:grade_id/fees' => 'grades#fees', via: :get, as: :fees
    resources :sponsors do
    collection do
      delete 'destroy_multiple'
    end
  end

      match'/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  resources :grades, :shallow => true do
collection do
     delete 'multipledelete'
end
    resources :batches do
collection do
     delete 'multipledelete'
end
      resources :lectures
    end
      resources :exams
      resources :lessons do
      resources :topics
    end

  end
 resources :subjects do
   collection do
     delete 'destroy_multiple'
   end
 end

  resources :states do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :cities do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :students do
    collection do
      delete 'destroy_multiple'
       post 'assign_batch_multiple'
    end
  end

  match'/students/:student_id/banmultiple' => 'students#banmultiple', :via => [:get, :put], as: :banmultiple
  match '/index_action' => 'students#index_action', :via => :get
  match '/grades/:grade_id/batches' => 'batches#index' 
  match'/students/:student_id/addmition' => 'students#addmition', :via => [:get, :post], as: :addmition

  match '/assign_batch' => 'students#assign_batch', :via => [:get, :post]
  match '/addgrade' => 'students#addgrade', :via => [:get, :post], as: :addgrade
  match '/student/:state_id/city' => 'students#city', :via => :get, as: :city
  match '/students/:grade_id/assign_batch_multiple' => 'students#assign_batch_multiple', :via => [:get, :post], as: :assign_batch_multiple
  match '/grade/:grade_id/subjects' => 'grades#subjects_list', :via => [:get, :post], as: :subjects_list
  match '/grade/:grade_id/batch/:batch_id/students' => 'batches#assignbatch', :via => [:get, :post], as: :assignbatch
    match '/:student_id/document' => 'students#document', via: :get
  match '/batch/:batch_id/assigntrainers' => 'batches#assigntrainers', :via => [:get, :post], as: :assigntrainers
  match '/exam/:exam_id/setpaper' => 'exams#setpaper', :via => [:get, :post], as: :setpaper
  match '/exam/:exam_id/setsubject' => 'exams#setsubject', :via => [:get, :post], as: :setsubject
 match '/exam/:exam_id/setting' => 'exams#setting', :via => [:get, :put], as: :setting
 match '/exam/:exam_id/currentpaper' => 'exams#currentpaper', :via => [:get, :put], as: :currentpaper
 match '/exam/:exam_id/giveexam' => 'exams#giveexam', :via => [:get, :post], as: :giveexam
  match '/result_id/result' => 'exams#result', :via => :get, as: :result
  match '/student/:student_id/allresults' => 'students#allresults', :via => :get, as: :allresults




  match '/grades/batch/:batch_id/attendents' => 'batches#attendents', :via => [:get, :post], as: :attendents

  match'/marking_pattens/:marking_patten_id' => 'grades#destroy_marking_patten', :via => :delete, as: :destroy_marking_patten
  match '/studentinfo' => 'enquiries#studentinfo', via: :get
  match'/grade/:grade_id/subjects/update_multiple' => 'grades#update_multiple', :via =>[:get, :put ], as: :update_multiple
  match'/enquiry/:enquiry_id/students/new' => 'students#enrollement', :via => :get, as: :enrollement


match '/trainers/:trainer_id/ability' => 'trainers#ability', :via => [:get, :post], as: :ability
match 'trainers/:trainer_id/display' => 'trainers#display', :via =>  :get, as: :display
match 'lectures/:lecture_id/details' => 'lectures#details', :via =>  :get, as: :details
match '/calenderhelp' => 'home#calenderhelp', :via => :get


root :to => 'home#index'









end


app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :batch
  has_many :results
  has_many :students, :through => :results
  attr_accessible :exam_date, :batch_id
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  # GET /exams
  # GET /exams.json
  load_and_authorize_resource

  def index
    @grade = Grade.find(params[:grade_id])
    @exams = @grade.exams

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exams }
    end
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @exam = Exam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exam }
    end
  end

  # GET /exams/new
  # GET /exams/new.json
  def new
    @grade = Grade.find(params[:grade_id])
    @exam = @grade.exams.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exam }
    end
  end

  # GET /exams/1/edit
  def edit
    @exam = Exam.find(params[:id])
  end

  # POST /exams
  # POST /exams.json
  def create
    @grade = Grade.find(params[:grade_id])
    @exam = @grade.exams.build
    @exam.discription = params[:exam][:discription]
    @exam.exam_date = params[:exam][:exam_date]
    @exam.exam_name = params[:exam][:exam_name]

    respond_to do |format|
      if @exam.save
      if params[:subjects] != nil
        params[:subjects].each do |subject|
          @es = ExamsSubjects.new()
          @es.exam_id = @exam.id
          @es.subject_id = subject
          if @es.save
          end
        end
      end
        format.html { redirect_to setpaper_path(@exam), notice: 'Congratulations! you could assign exam for this grade. ' }

      else
        format.html { render action: "new" }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end
  def setpaper
  @exam = Exam.find(params[:exam_id])
    if request.post?
      @paper = Paper.new()
      @paper.exam_id = @exam.id
    @paper.paper_name = params[:paperName]
      if @paper.save
      if params[:questions] != nil
        params[:questions].each do |q|
        @question = Question.find(q)

        @question.paper_id = @paper.id
        if @question.save
    end
    end
    end
    redirect_to grades_path
    end
    end
  end
  def setting
    @exam = Exam.find(params[:exam_id])
    @paper = @exam.papers.where(:attempt_flag => nil)
    if request.put?
      if params[:papers] != nil
        params[:papers].each do |p|
          @paper = Paper.find(p)
          @paper.attempt_flag = true
          if @paper.save
        end
        end
  end
    redirect_to currentpaper_path(@exam)

    end
  end
  def currentpaper
    @exam = Exam.find(params[:exam_id])
    @paper = @exam.papers.where(:attempt_flag => nil)
    if request.put?
      @p = Paper.find(params[:paper])
      @p.current_paper_flag = true
      if @p.save
        redirect_to grades_path
      end
    end
  end
  def giveexam
    @questions_count = []
    @exam = Exam.find(params[:exam_id])
    @paper = @exam.papers.where(:current_paper_flag => true)
    @paper.last.questions.each do |q|
      @questions_count.push(q.id)
    end
    if request.post?
      @attempt = Attempt.new()
      @attempt.paper_id = @paper.last.id
      @attempt.student_id = current_user.student.id
      @attempt.total_marks = @questions_count.size * 2

      if @attempt.save
        @paper.last.questions.each_index do |i|
          p 'q var is,'
          @q = @paper.last.questions[i]
          if params[@q.id.to_s]
            @option = Option.find(params[@q.id.to_s])
            @option.attempt_id = @attempt.id
            if @option.save
            end
          end
      end
        @get_marks = @attempt.options.where(:option_right => true)
        @calculate_marks = @get_marks.size * 2
        @result = Result.new()
        if @attempt.total_marks > 1 && @attempt.total_marks <= 10 && @calculate_marks >= 4
          @result.result_status = "pass"
          @result.get_marks = @calculate_marks
          @result.min_marks = 4
          @result.total_marks = @attempt.total_marks
        elsif @attempt.total_marks > 10 && @attempt.total_marks <= 20 && @calculate_marks >= 8
          @result.result_status = "pass"
          @result.get_marks = @calculate_marks
          @result.min_marks = 8
          @result.total_marks = @attempt.total_marks

          elsif @attempt.total_marks > 20 && @attempt.total_marks <= 30 && @calculate_marks >= 12
          @result.result_status = "pass"
        @result.get_marks = @calculate_marks
          @result.min_marks = 12
          @result.total_marks = @attempt.total_marks

       elsif @attempt.total_marks > 30 && @attempt.total_marks <= 40 && @calculate_marks >= 16
        @result.result_status = "pass"
          @result.get_marks = @calculate_marks
          @result.min_marks = 16
          @result.total_marks = @attempt.total_marks
        elsif @attempt.total_marks > 40 && @attempt.total_marks <= 50 && @calculate_marks >= 20
          @result.result_status = "pass"
          @result.get_marks = @calculate_marks
          @result.min_marks = 20
          @result.total_marks = @attempt.total_marks
        elsif @attempt.total_marks > 50 && @attempt.total_marks <= 60 && @calculate_marks >= 24
          @result.total_marks = @attempt.total_marks
          @result.result_status = "pass"
          @result.min_marks = 24
          @result.get_marks = @calculate_marks
        elsif @attempt.total_marks > 60 && @attempt.total_marks <= 70 && @calculate_marks >= 28
          @result.total_marks = @attempt.total_marks
          @result.result_status = "pass"
          @result.min_marks = 28
          @result.get_marks = @calculate_marks
        elsif @attempt.total_marks > 70 && @attempt.total_marks <= 80 && calculate_marks >= 32
          @result.total_marks = @attempt.total_marks
          @result.result_status = "pass"
          @result.min_marks = 32
          @result.get_marks = @calculate_marks
        elsif @attempt.total_marks > 80 && @attempt.total_marks <= 90 && @calculate_marks >= 36
          @result.total_marks = @attempt.total_marks
          @result.result_status = "pass"
          @result.min_marks = 36
          @result.get_marks = @calculate_marks
        elsif @attempt.total_marks > 90 && @attempt.total_marks <= 100 && @calculate_marks >= 40
          @result.min_marks = 40
          @result.result_status = "pass"
          @result.get_marks = @calculate_marks
          @result.total_marks = @attempt.total_marks
        elsif @calculate_marks == 0
        @result.result_status = "fail"
          @result.get_marks = @calculate_marks
          @result.total_marks = @attempt.total_marks
        else
          @result.result_status = "fail"
          @result.get_marks = @calculate_marks
          @result.total_marks = @attempt.total_marks
        end
        @result.attempt_id = @attempt.id
        if @result.save
        redirect_to result_path(@result)
        r = @result
        user = User.where(:roles => 'admin').collect(&:email)

        UserMailer.examreport(user, r).deliver
        end
  end
   end
  end
  def result
    @result = Result.find(params[:format])
  end
  # PUT /exams/1
  # PUT /exams/1.json
  def update
    @exam = Exam.find(params[:id])

    respond_to do |format|
      if @exam.update_attributes(params[:exam])
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy

    respond_to do |format|
      format.html { redirect_to exams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.haml
- content_for :javascript do
  = javascript_include_tag 'setup_exam_date'
= simple_form_for([@grade, @exam]) do |f|
  = f.error_notification

  .form-inputs
    = f.hidden_field :grade_id
    = f.input :exam_name
    = f.input :exam_date, :label => 'Exam Date' do
      = f.input_field :exam_date, :readonly => true, :as => :datepicker
      %a{:href => '#', :id => 'imgCalendar_exam_date', :class => 'datePicker'}
        = image_tag('Calendar_scheduleHS.png', :alt => 'Pick date from calendar' )
        = link_to 'Need Help?', calenderhelp_path, "data-toggle" => "modal", "data-target" => "#calendermodel", :class => "lnkApprove", :remote => true, :class => 'btn btn-mini'
    = f.input :discription, as: :text
    %h2 Select Subjects for this exam
    - @grade.subjects.each do |s|
      = check_box_tag "subjects[]", s.id
      = s.subject
  .form-actions
    = submit_tag "Next"

    %div{:id => 'calendermodel', :class => 'modal hide fade-calenderhelp', :tabindex => '-1', :role => 'dialog', 'aria-labelledby' => 'myModalLabel', 'aria-hidden' => 'true'}
      %div{:class => 'modal-header-calenderhelp'}
        %h3 Instructions:      

      %div{:class => 'modal-body'}
        %div{:class => 'modal-footer-calenderhelp'}


app/views/exams/currentpaper.html.haml
%h1 Tell us your current paper:
= simple_form_for currentpaper_path, method: :put do |f|
  = select_tag "paper", options_for_select(@paper.collect{ |p| [p.paper_name, p.id]})
  = submit_tag "Save"

app/views/exams/edit.html.haml
%h1 Editing exam

= render 'form'

= link_to 'Show', @exam
\|
= link_to 'Back', exams_path

app/views/exams/giveexam.html.haml
- content_for :javascript do
  = javascript_include_tag 'giveexam'
%h1 Instructions for exam:
%ol
  %li The paper is designed in #{@paper.last.exam.subjects.size} subjects.
  %ul
    - @paper.last.exam.subjects.each do |s|
      %li= s.subject
  %li All these sections will carries few questions based on the marks.
  %li Students will get time span of 40 minutes to solve the exam, extra 10 minutes will be given to recheck their paper.
  %li Each question will comes under heading level 3 followed by several radio buttons. Student  needs to choose only one options to give correct answer to check radio button, by pressing spacebar an answer can be given.
  %li While writing the entire exam students are not allow to use other keys on the keyboard, except "up arrow, down arrow and spacebar".
  %li If student is observed pressing any keys except above mention keys on the keyboard, they will be rejected from course;.
- @hold_array = []
- @paper.last.questions.each do |q|
  - @hold_array.push(q.id)
- @questions_count = @hold_array.size
= simple_form_for giveexam_path, method: :post do |f|
  %i total marks of this exams is: #{@questions_count * 2}
  = hidden_field_tag 'student_id', current_user.student.id
  - @paper.last.questions.each do |q|
    %h3= q.question_name
    - q.options.each do |o|
      = radio_button_tag q.id, o.id
      = o.option_name
  = submit_tag "Submit"

app/views/exams/index.html.haml
%h1 Showing all exams

%table
  %tr
    %th Exam Name
    %th Exam Date
    %th Action

  - @exams.each do |exam|
    %tr
      %td= exam.exam_name
      %td= exam.exam_date
      - if current_user.roles != 'student'
        %td= link_to "Set paper", setpaper_path(exam)
        %td= link_to "Change setting of paper", setting_path(exam)
      - elsif current_user.roles == 'student'
        - if Date.today == exam.exam_date
          %td= link_to "Give exam", giveexam_path(exam)

%br

- if current_user.roles != 'student'
  = link_to 'New Exam', new_grade_exam_path

app/views/exams/new.html.haml
%h1 New exam

= render 'form'

= link_to 'Back', grade_exams_path

app/views/exams/result.html.haml
%h1 Result
- if @result.result_status == "pass"
  %i Congratulations! you have successfully clear this exam!!!
  %br
  %h2 Result details:
  %table.table
    %tr
      %th Student name
      %th Total marks
      %th Minimum marks
      %th Obtained marks
      %th Result status
    %tr
      %td= @result.attempt.student.first_name.capitalize + " " + @result.attempt.student.last_name.capitalize
      %td= @result.total_marks
      %td= @result.min_marks
      %td= @result.get_marks
      %td= @result.result_status.capitalize
- elsif @result.result_status == "fail"
  %i Sorry, you have not clear this exam :(
  %br
  %h2 Result details:
  %table.table
    %tr
      %th Student name
      %th Total marks
      %th Obtained marks
      %th Result status
    %tr
      %td= @result.attempt.student.first_name.capitalize + " " + @result.attempt.student.last_name.capitalize
      %td= @result.total_marks
      %td= @result.get_marks
      %td= @result.result_status.capitalize
  %i Please try again. All the best for your future.

app/views/exams/setpaper.html.haml
%h1 Set Questions for this exam:
= simple_form_for setpaper_path(@exam), method: :post do |f|
  = label_tag 'Paper name'
  = text_field_tag 'paperName'
  - @exam.subjects.each do |subject|
    %h2 Questions under #{subject.subject} subject
    - subject.questions.each do |question|
      = check_box_tag "questions[]", question.id
      = question.question_name
  = submit_tag "Save"

app/views/exams/setsubject.html.haml
%h2 Select subjects for this exam
= simple_form_for setsubject_path, method: :post do |f|
  - @exam.grade.subjects.each do |s|
    = check_box_tag "subjects[]", s.id
    = s.subject
  = submit_tag "Next"

app/views/exams/setting.html.haml
%h1 Select attempted papers of this exam:
= simple_form_for setting_path, method: :put do |f|
  - @paper.each do |p|
    = check_box_tag "papers[]", p.id
    = p.paper_name
  = submit_tag "Next"

app/views/exams/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_exam_path(@exam)
\|
= link_to 'Back', exams_path